### ISSUE TITLE
[Feature] Compatibility with Builder's Delight

### ISSUE THREAD

**Issue by A00826925** [SuperMartijn642/Rechiseled#21]
Recently i found out there's another chisel mod called "Builder's delight", I know this might be too much to ask but having to use 2 chisels is annoying, maybe let those mod's blocks be crafted using your chisel? or the other way around, would be cool to see.

**Comment by SuperMartijn642** [comment]
Builder's Delight does not have an api for interacting with its chisel's recipes, so such compatibility might not be possible at all on my end or might break every time they update.
Additionally, Builder's Delight is only available for 1.18.2 and 1.19.2. Rechiseled is available for 1.12, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19.2, and 1.19.3. I develop simultaneously for all those versions, so to make that a bit easier, I like to keep all branches as similar as possible. Adding compatibility with Builder's Delight for 1.18 and 1.19.2 is certainly possible, but it makes it a bit of a hassle as those branches will then differ from the rest.

Rechiseled does have a stable api for requesting and interacting with chiseling recipes, so Builder's Delight is free to add compatibility if they want to.

For now, I will not be adding interoperability with Builder's Delight's chisel mainly because they don't have an api. If they do create a stable api, I might reconsider.
