### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by Zane0116** [SuperMartijn642/Rechiseled#55]
**Version Info**
- Minecraft, 1.20.1
- Rechiseled, 1.1.4-forge

**Description of the Bug**
some of the icons of blocks are missing and when placed down are messed up

**Steps to Reproduce**
im not sure how to reproduce this

**Screenshots**
![2023-09-24_01 18 28](https://github.com/SuperMartijn642/Rechiseled/assets/116866882/54511060-d909-4315-a386-2966ab2cdd16)
![Screenshot 2023-09-24 011904](https://github.com/SuperMartijn642/Rechiseled/assets/116866882/d7580574-bb8b-4807-9b90-bf1e77056d6e)

**Comment by Zane0116** [comment]
![Screenshot 2023-09-24 013253](https://github.com/SuperMartijn642/Rechiseled/assets/116866882/fa362f2a-d977-49cc-8444-6a95c6f2ca1b)
here is one of the error logs

**Comment by SuperMartijn642** [comment]
What version of Fusion are you using?
Also what other mods are you using and could you share the entire log?

**Comment by Zane0116** [comment]
Fusion is 1.0.5a-forge
![Screenshot 2023-09-24 080543](https://github.com/SuperMartijn642/Rechiseled/assets/116866882/c2f18d5a-4c73-466b-ae8b-970f78202f33)
![Screenshot 2023-09-24 080601](https://github.com/SuperMartijn642/Rechiseled/assets/116866882/8eb201ff-044f-4508-9f22-dac0d3b25371)
![Screenshot 2023-09-24 080610](https://github.com/SuperMartijn642/Rechiseled/assets/116866882/4f8ba3ef-fef9-44be-9f9a-224e97a80399)
[latest.log](https://github.com/SuperMartijn642/Rechiseled/files/12708556/latest.log)

**Comment by SuperMartijn642** [comment]
Seems to be caused by `Fusion-1.20.1-6.0.0.3.jar`. That mod uses the same modid as Fusion, the dependency for Rechiseled.
Since Forge sees two files with the same modid, it assumes it is the same mod and only loads the one with the highest version. The version for `Fusion-1.20.1-6.0.0.3.jar` is 6.0.0.3 while for my Fusion, it is only 1.0.5a.
Thus, Fusion, the dependency for Rechiseled, does not get loaded.

Sadly, not much I can do about it as both mods happen to have the same modid.
