### ISSUE TITLE
[Question] Fusion on serverside needs :(

### ISSUE THREAD

**Issue by LeoDemitori** [SuperMartijn642/Rechiseled#63]
**Question**
Why does the Rechiseled require a Fusion mod on the serverSide?
The server does not start without this client mod

**Comment by SuperMartijn642** [comment]
Fabric does not allow specifying a dependency for only one side. It has to be required on either both the server and the client or on neither.
I went with the former as otherwise people would try to use Rechiseled without Fusion on the client without realizing it.

Fusion can be installed on the server just fine, it just won't do anything, so until Fabric allows specifying dependencies for only one side, you'll just have to install Fusion on the server as well.
